# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/data3/zhangys/MyProject_CUDA/My_CUDA_gemm_All_version

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/data3/zhangys/MyProject_CUDA/My_CUDA_gemm_All_version

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data3/zhangys/MyProject_CUDA/My_CUDA_gemm_All_version/CMakeFiles /data/data3/zhangys/MyProject_CUDA/My_CUDA_gemm_All_version//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data3/zhangys/MyProject_CUDA/My_CUDA_gemm_All_version/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cublas_test.out

# Build rule for target.
cublas_test.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cublas_test.out
.PHONY : cublas_test.out

# fast build rule for target.
cublas_test.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cublas_test.out.dir/build.make CMakeFiles/cublas_test.out.dir/build
.PHONY : cublas_test.out/fast

#=============================================================================
# Target rules for targets named gemm_ALL.out

# Build rule for target.
gemm_ALL.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_ALL.out
.PHONY : gemm_ALL.out

# fast build rule for target.
gemm_ALL.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_ALL.out.dir/build.make CMakeFiles/gemm_ALL.out.dir/build
.PHONY : gemm_ALL.out/fast

#=============================================================================
# Target rules for targets named gemm_alter.out

# Build rule for target.
gemm_alter.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_alter.out
.PHONY : gemm_alter.out

# fast build rule for target.
gemm_alter.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_alter.out.dir/build.make CMakeFiles/gemm_alter.out.dir/build
.PHONY : gemm_alter.out/fast

#=============================================================================
# Target rules for targets named gemm_v1.out

# Build rule for target.
gemm_v1.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v1.out
.PHONY : gemm_v1.out

# fast build rule for target.
gemm_v1.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v1.out.dir/build.make CMakeFiles/gemm_v1.out.dir/build
.PHONY : gemm_v1.out/fast

#=============================================================================
# Target rules for targets named gemm_v1_alter.out

# Build rule for target.
gemm_v1_alter.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v1_alter.out
.PHONY : gemm_v1_alter.out

# fast build rule for target.
gemm_v1_alter.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v1_alter.out.dir/build.make CMakeFiles/gemm_v1_alter.out.dir/build
.PHONY : gemm_v1_alter.out/fast

#=============================================================================
# Target rules for targets named gemm_v2.out

# Build rule for target.
gemm_v2.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v2.out
.PHONY : gemm_v2.out

# fast build rule for target.
gemm_v2.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v2.out.dir/build.make CMakeFiles/gemm_v2.out.dir/build
.PHONY : gemm_v2.out/fast

#=============================================================================
# Target rules for targets named gemm_v3.out

# Build rule for target.
gemm_v3.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v3.out
.PHONY : gemm_v3.out

# fast build rule for target.
gemm_v3.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v3.out.dir/build.make CMakeFiles/gemm_v3.out.dir/build
.PHONY : gemm_v3.out/fast

#=============================================================================
# Target rules for targets named gemm_v4.out

# Build rule for target.
gemm_v4.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v4.out
.PHONY : gemm_v4.out

# fast build rule for target.
gemm_v4.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v4.out.dir/build.make CMakeFiles/gemm_v4.out.dir/build
.PHONY : gemm_v4.out/fast

#=============================================================================
# Target rules for targets named gemm_v5.out

# Build rule for target.
gemm_v5.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v5.out
.PHONY : gemm_v5.out

# fast build rule for target.
gemm_v5.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v5.out.dir/build.make CMakeFiles/gemm_v5.out.dir/build
.PHONY : gemm_v5.out/fast

#=============================================================================
# Target rules for targets named gemm_v6.out

# Build rule for target.
gemm_v6.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v6.out
.PHONY : gemm_v6.out

# fast build rule for target.
gemm_v6.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v6.out.dir/build.make CMakeFiles/gemm_v6.out.dir/build
.PHONY : gemm_v6.out/fast

#=============================================================================
# Target rules for targets named gemm_v6_alter.out

# Build rule for target.
gemm_v6_alter.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v6_alter.out
.PHONY : gemm_v6_alter.out

# fast build rule for target.
gemm_v6_alter.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v6_alter.out.dir/build.make CMakeFiles/gemm_v6_alter.out.dir/build
.PHONY : gemm_v6_alter.out/fast

#=============================================================================
# Target rules for targets named gemm_v7.out

# Build rule for target.
gemm_v7.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v7.out
.PHONY : gemm_v7.out

# fast build rule for target.
gemm_v7.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v7.out.dir/build.make CMakeFiles/gemm_v7.out.dir/build
.PHONY : gemm_v7.out/fast

#=============================================================================
# Target rules for targets named gemm_v7_alter.out

# Build rule for target.
gemm_v7_alter.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v7_alter.out
.PHONY : gemm_v7_alter.out

# fast build rule for target.
gemm_v7_alter.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v7_alter.out.dir/build.make CMakeFiles/gemm_v7_alter.out.dir/build
.PHONY : gemm_v7_alter.out/fast

#=============================================================================
# Target rules for targets named gemm_v8.out

# Build rule for target.
gemm_v8.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v8.out
.PHONY : gemm_v8.out

# fast build rule for target.
gemm_v8.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v8.out.dir/build.make CMakeFiles/gemm_v8.out.dir/build
.PHONY : gemm_v8.out/fast

#=============================================================================
# Target rules for targets named gemm_v8_alter.out

# Build rule for target.
gemm_v8_alter.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v8_alter.out
.PHONY : gemm_v8_alter.out

# fast build rule for target.
gemm_v8_alter.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v8_alter.out.dir/build.make CMakeFiles/gemm_v8_alter.out.dir/build
.PHONY : gemm_v8_alter.out/fast

#=============================================================================
# Target rules for targets named gemm_v9.out

# Build rule for target.
gemm_v9.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v9.out
.PHONY : gemm_v9.out

# fast build rule for target.
gemm_v9.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v9.out.dir/build.make CMakeFiles/gemm_v9.out.dir/build
.PHONY : gemm_v9.out/fast

#=============================================================================
# Target rules for targets named gemm_v9_alter.out

# Build rule for target.
gemm_v9_alter.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemm_v9_alter.out
.PHONY : gemm_v9_alter.out

# fast build rule for target.
gemm_v9_alter.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v9_alter.out.dir/build.make CMakeFiles/gemm_v9_alter.out.dir/build
.PHONY : gemm_v9_alter.out/fast

#=============================================================================
# Target rules for targets named test.out

# Build rule for target.
test.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test.out
.PHONY : test.out

# fast build rule for target.
test.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/build
.PHONY : test.out/fast

cublas_test.o: cublas_test.cu.o
.PHONY : cublas_test.o

# target to build an object file
cublas_test.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cublas_test.out.dir/build.make CMakeFiles/cublas_test.out.dir/cublas_test.cu.o
.PHONY : cublas_test.cu.o

cublas_test.i: cublas_test.cu.i
.PHONY : cublas_test.i

# target to preprocess a source file
cublas_test.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cublas_test.out.dir/build.make CMakeFiles/cublas_test.out.dir/cublas_test.cu.i
.PHONY : cublas_test.cu.i

cublas_test.s: cublas_test.cu.s
.PHONY : cublas_test.s

# target to generate assembly for a file
cublas_test.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cublas_test.out.dir/build.make CMakeFiles/cublas_test.out.dir/cublas_test.cu.s
.PHONY : cublas_test.cu.s

gemm_ALL.o: gemm_ALL.cu.o
.PHONY : gemm_ALL.o

# target to build an object file
gemm_ALL.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_ALL.out.dir/build.make CMakeFiles/gemm_ALL.out.dir/gemm_ALL.cu.o
.PHONY : gemm_ALL.cu.o

gemm_ALL.i: gemm_ALL.cu.i
.PHONY : gemm_ALL.i

# target to preprocess a source file
gemm_ALL.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_ALL.out.dir/build.make CMakeFiles/gemm_ALL.out.dir/gemm_ALL.cu.i
.PHONY : gemm_ALL.cu.i

gemm_ALL.s: gemm_ALL.cu.s
.PHONY : gemm_ALL.s

# target to generate assembly for a file
gemm_ALL.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_ALL.out.dir/build.make CMakeFiles/gemm_ALL.out.dir/gemm_ALL.cu.s
.PHONY : gemm_ALL.cu.s

gemm_alter.o: gemm_alter.cu.o
.PHONY : gemm_alter.o

# target to build an object file
gemm_alter.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_alter.out.dir/build.make CMakeFiles/gemm_alter.out.dir/gemm_alter.cu.o
.PHONY : gemm_alter.cu.o

gemm_alter.i: gemm_alter.cu.i
.PHONY : gemm_alter.i

# target to preprocess a source file
gemm_alter.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_alter.out.dir/build.make CMakeFiles/gemm_alter.out.dir/gemm_alter.cu.i
.PHONY : gemm_alter.cu.i

gemm_alter.s: gemm_alter.cu.s
.PHONY : gemm_alter.s

# target to generate assembly for a file
gemm_alter.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_alter.out.dir/build.make CMakeFiles/gemm_alter.out.dir/gemm_alter.cu.s
.PHONY : gemm_alter.cu.s

gemm_v1.o: gemm_v1.cu.o
.PHONY : gemm_v1.o

# target to build an object file
gemm_v1.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v1.out.dir/build.make CMakeFiles/gemm_v1.out.dir/gemm_v1.cu.o
.PHONY : gemm_v1.cu.o

gemm_v1.i: gemm_v1.cu.i
.PHONY : gemm_v1.i

# target to preprocess a source file
gemm_v1.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v1.out.dir/build.make CMakeFiles/gemm_v1.out.dir/gemm_v1.cu.i
.PHONY : gemm_v1.cu.i

gemm_v1.s: gemm_v1.cu.s
.PHONY : gemm_v1.s

# target to generate assembly for a file
gemm_v1.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v1.out.dir/build.make CMakeFiles/gemm_v1.out.dir/gemm_v1.cu.s
.PHONY : gemm_v1.cu.s

gemm_v1_alter.o: gemm_v1_alter.cu.o
.PHONY : gemm_v1_alter.o

# target to build an object file
gemm_v1_alter.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v1_alter.out.dir/build.make CMakeFiles/gemm_v1_alter.out.dir/gemm_v1_alter.cu.o
.PHONY : gemm_v1_alter.cu.o

gemm_v1_alter.i: gemm_v1_alter.cu.i
.PHONY : gemm_v1_alter.i

# target to preprocess a source file
gemm_v1_alter.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v1_alter.out.dir/build.make CMakeFiles/gemm_v1_alter.out.dir/gemm_v1_alter.cu.i
.PHONY : gemm_v1_alter.cu.i

gemm_v1_alter.s: gemm_v1_alter.cu.s
.PHONY : gemm_v1_alter.s

# target to generate assembly for a file
gemm_v1_alter.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v1_alter.out.dir/build.make CMakeFiles/gemm_v1_alter.out.dir/gemm_v1_alter.cu.s
.PHONY : gemm_v1_alter.cu.s

gemm_v2.o: gemm_v2.cu.o
.PHONY : gemm_v2.o

# target to build an object file
gemm_v2.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v2.out.dir/build.make CMakeFiles/gemm_v2.out.dir/gemm_v2.cu.o
.PHONY : gemm_v2.cu.o

gemm_v2.i: gemm_v2.cu.i
.PHONY : gemm_v2.i

# target to preprocess a source file
gemm_v2.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v2.out.dir/build.make CMakeFiles/gemm_v2.out.dir/gemm_v2.cu.i
.PHONY : gemm_v2.cu.i

gemm_v2.s: gemm_v2.cu.s
.PHONY : gemm_v2.s

# target to generate assembly for a file
gemm_v2.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v2.out.dir/build.make CMakeFiles/gemm_v2.out.dir/gemm_v2.cu.s
.PHONY : gemm_v2.cu.s

gemm_v3.o: gemm_v3.cu.o
.PHONY : gemm_v3.o

# target to build an object file
gemm_v3.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v3.out.dir/build.make CMakeFiles/gemm_v3.out.dir/gemm_v3.cu.o
.PHONY : gemm_v3.cu.o

gemm_v3.i: gemm_v3.cu.i
.PHONY : gemm_v3.i

# target to preprocess a source file
gemm_v3.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v3.out.dir/build.make CMakeFiles/gemm_v3.out.dir/gemm_v3.cu.i
.PHONY : gemm_v3.cu.i

gemm_v3.s: gemm_v3.cu.s
.PHONY : gemm_v3.s

# target to generate assembly for a file
gemm_v3.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v3.out.dir/build.make CMakeFiles/gemm_v3.out.dir/gemm_v3.cu.s
.PHONY : gemm_v3.cu.s

gemm_v4.o: gemm_v4.cu.o
.PHONY : gemm_v4.o

# target to build an object file
gemm_v4.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v4.out.dir/build.make CMakeFiles/gemm_v4.out.dir/gemm_v4.cu.o
.PHONY : gemm_v4.cu.o

gemm_v4.i: gemm_v4.cu.i
.PHONY : gemm_v4.i

# target to preprocess a source file
gemm_v4.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v4.out.dir/build.make CMakeFiles/gemm_v4.out.dir/gemm_v4.cu.i
.PHONY : gemm_v4.cu.i

gemm_v4.s: gemm_v4.cu.s
.PHONY : gemm_v4.s

# target to generate assembly for a file
gemm_v4.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v4.out.dir/build.make CMakeFiles/gemm_v4.out.dir/gemm_v4.cu.s
.PHONY : gemm_v4.cu.s

gemm_v5.o: gemm_v5.cu.o
.PHONY : gemm_v5.o

# target to build an object file
gemm_v5.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v5.out.dir/build.make CMakeFiles/gemm_v5.out.dir/gemm_v5.cu.o
.PHONY : gemm_v5.cu.o

gemm_v5.i: gemm_v5.cu.i
.PHONY : gemm_v5.i

# target to preprocess a source file
gemm_v5.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v5.out.dir/build.make CMakeFiles/gemm_v5.out.dir/gemm_v5.cu.i
.PHONY : gemm_v5.cu.i

gemm_v5.s: gemm_v5.cu.s
.PHONY : gemm_v5.s

# target to generate assembly for a file
gemm_v5.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v5.out.dir/build.make CMakeFiles/gemm_v5.out.dir/gemm_v5.cu.s
.PHONY : gemm_v5.cu.s

gemm_v6.o: gemm_v6.cu.o
.PHONY : gemm_v6.o

# target to build an object file
gemm_v6.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v6.out.dir/build.make CMakeFiles/gemm_v6.out.dir/gemm_v6.cu.o
.PHONY : gemm_v6.cu.o

gemm_v6.i: gemm_v6.cu.i
.PHONY : gemm_v6.i

# target to preprocess a source file
gemm_v6.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v6.out.dir/build.make CMakeFiles/gemm_v6.out.dir/gemm_v6.cu.i
.PHONY : gemm_v6.cu.i

gemm_v6.s: gemm_v6.cu.s
.PHONY : gemm_v6.s

# target to generate assembly for a file
gemm_v6.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v6.out.dir/build.make CMakeFiles/gemm_v6.out.dir/gemm_v6.cu.s
.PHONY : gemm_v6.cu.s

gemm_v6_alter.o: gemm_v6_alter.cu.o
.PHONY : gemm_v6_alter.o

# target to build an object file
gemm_v6_alter.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v6_alter.out.dir/build.make CMakeFiles/gemm_v6_alter.out.dir/gemm_v6_alter.cu.o
.PHONY : gemm_v6_alter.cu.o

gemm_v6_alter.i: gemm_v6_alter.cu.i
.PHONY : gemm_v6_alter.i

# target to preprocess a source file
gemm_v6_alter.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v6_alter.out.dir/build.make CMakeFiles/gemm_v6_alter.out.dir/gemm_v6_alter.cu.i
.PHONY : gemm_v6_alter.cu.i

gemm_v6_alter.s: gemm_v6_alter.cu.s
.PHONY : gemm_v6_alter.s

# target to generate assembly for a file
gemm_v6_alter.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v6_alter.out.dir/build.make CMakeFiles/gemm_v6_alter.out.dir/gemm_v6_alter.cu.s
.PHONY : gemm_v6_alter.cu.s

gemm_v7.o: gemm_v7.cu.o
.PHONY : gemm_v7.o

# target to build an object file
gemm_v7.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v7.out.dir/build.make CMakeFiles/gemm_v7.out.dir/gemm_v7.cu.o
.PHONY : gemm_v7.cu.o

gemm_v7.i: gemm_v7.cu.i
.PHONY : gemm_v7.i

# target to preprocess a source file
gemm_v7.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v7.out.dir/build.make CMakeFiles/gemm_v7.out.dir/gemm_v7.cu.i
.PHONY : gemm_v7.cu.i

gemm_v7.s: gemm_v7.cu.s
.PHONY : gemm_v7.s

# target to generate assembly for a file
gemm_v7.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v7.out.dir/build.make CMakeFiles/gemm_v7.out.dir/gemm_v7.cu.s
.PHONY : gemm_v7.cu.s

gemm_v7_alter.o: gemm_v7_alter.cu.o
.PHONY : gemm_v7_alter.o

# target to build an object file
gemm_v7_alter.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v7_alter.out.dir/build.make CMakeFiles/gemm_v7_alter.out.dir/gemm_v7_alter.cu.o
.PHONY : gemm_v7_alter.cu.o

gemm_v7_alter.i: gemm_v7_alter.cu.i
.PHONY : gemm_v7_alter.i

# target to preprocess a source file
gemm_v7_alter.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v7_alter.out.dir/build.make CMakeFiles/gemm_v7_alter.out.dir/gemm_v7_alter.cu.i
.PHONY : gemm_v7_alter.cu.i

gemm_v7_alter.s: gemm_v7_alter.cu.s
.PHONY : gemm_v7_alter.s

# target to generate assembly for a file
gemm_v7_alter.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v7_alter.out.dir/build.make CMakeFiles/gemm_v7_alter.out.dir/gemm_v7_alter.cu.s
.PHONY : gemm_v7_alter.cu.s

gemm_v8.o: gemm_v8.cu.o
.PHONY : gemm_v8.o

# target to build an object file
gemm_v8.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v8.out.dir/build.make CMakeFiles/gemm_v8.out.dir/gemm_v8.cu.o
.PHONY : gemm_v8.cu.o

gemm_v8.i: gemm_v8.cu.i
.PHONY : gemm_v8.i

# target to preprocess a source file
gemm_v8.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v8.out.dir/build.make CMakeFiles/gemm_v8.out.dir/gemm_v8.cu.i
.PHONY : gemm_v8.cu.i

gemm_v8.s: gemm_v8.cu.s
.PHONY : gemm_v8.s

# target to generate assembly for a file
gemm_v8.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v8.out.dir/build.make CMakeFiles/gemm_v8.out.dir/gemm_v8.cu.s
.PHONY : gemm_v8.cu.s

gemm_v8_alter.o: gemm_v8_alter.cu.o
.PHONY : gemm_v8_alter.o

# target to build an object file
gemm_v8_alter.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v8_alter.out.dir/build.make CMakeFiles/gemm_v8_alter.out.dir/gemm_v8_alter.cu.o
.PHONY : gemm_v8_alter.cu.o

gemm_v8_alter.i: gemm_v8_alter.cu.i
.PHONY : gemm_v8_alter.i

# target to preprocess a source file
gemm_v8_alter.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v8_alter.out.dir/build.make CMakeFiles/gemm_v8_alter.out.dir/gemm_v8_alter.cu.i
.PHONY : gemm_v8_alter.cu.i

gemm_v8_alter.s: gemm_v8_alter.cu.s
.PHONY : gemm_v8_alter.s

# target to generate assembly for a file
gemm_v8_alter.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v8_alter.out.dir/build.make CMakeFiles/gemm_v8_alter.out.dir/gemm_v8_alter.cu.s
.PHONY : gemm_v8_alter.cu.s

gemm_v9.o: gemm_v9.cu.o
.PHONY : gemm_v9.o

# target to build an object file
gemm_v9.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v9.out.dir/build.make CMakeFiles/gemm_v9.out.dir/gemm_v9.cu.o
.PHONY : gemm_v9.cu.o

gemm_v9.i: gemm_v9.cu.i
.PHONY : gemm_v9.i

# target to preprocess a source file
gemm_v9.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v9.out.dir/build.make CMakeFiles/gemm_v9.out.dir/gemm_v9.cu.i
.PHONY : gemm_v9.cu.i

gemm_v9.s: gemm_v9.cu.s
.PHONY : gemm_v9.s

# target to generate assembly for a file
gemm_v9.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v9.out.dir/build.make CMakeFiles/gemm_v9.out.dir/gemm_v9.cu.s
.PHONY : gemm_v9.cu.s

gemm_v9_alter.o: gemm_v9_alter.cu.o
.PHONY : gemm_v9_alter.o

# target to build an object file
gemm_v9_alter.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v9_alter.out.dir/build.make CMakeFiles/gemm_v9_alter.out.dir/gemm_v9_alter.cu.o
.PHONY : gemm_v9_alter.cu.o

gemm_v9_alter.i: gemm_v9_alter.cu.i
.PHONY : gemm_v9_alter.i

# target to preprocess a source file
gemm_v9_alter.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v9_alter.out.dir/build.make CMakeFiles/gemm_v9_alter.out.dir/gemm_v9_alter.cu.i
.PHONY : gemm_v9_alter.cu.i

gemm_v9_alter.s: gemm_v9_alter.cu.s
.PHONY : gemm_v9_alter.s

# target to generate assembly for a file
gemm_v9_alter.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemm_v9_alter.out.dir/build.make CMakeFiles/gemm_v9_alter.out.dir/gemm_v9_alter.cu.s
.PHONY : gemm_v9_alter.cu.s

test.o: test.cu.o
.PHONY : test.o

# target to build an object file
test.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/test.cu.o
.PHONY : test.cu.o

test.i: test.cu.i
.PHONY : test.i

# target to preprocess a source file
test.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/test.cu.i
.PHONY : test.cu.i

test.s: test.cu.s
.PHONY : test.s

# target to generate assembly for a file
test.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.out.dir/build.make CMakeFiles/test.out.dir/test.cu.s
.PHONY : test.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cublas_test.out"
	@echo "... gemm_ALL.out"
	@echo "... gemm_alter.out"
	@echo "... gemm_v1.out"
	@echo "... gemm_v1_alter.out"
	@echo "... gemm_v2.out"
	@echo "... gemm_v3.out"
	@echo "... gemm_v4.out"
	@echo "... gemm_v5.out"
	@echo "... gemm_v6.out"
	@echo "... gemm_v6_alter.out"
	@echo "... gemm_v7.out"
	@echo "... gemm_v7_alter.out"
	@echo "... gemm_v8.out"
	@echo "... gemm_v8_alter.out"
	@echo "... gemm_v9.out"
	@echo "... gemm_v9_alter.out"
	@echo "... test.out"
	@echo "... cublas_test.o"
	@echo "... cublas_test.i"
	@echo "... cublas_test.s"
	@echo "... gemm_ALL.o"
	@echo "... gemm_ALL.i"
	@echo "... gemm_ALL.s"
	@echo "... gemm_alter.o"
	@echo "... gemm_alter.i"
	@echo "... gemm_alter.s"
	@echo "... gemm_v1.o"
	@echo "... gemm_v1.i"
	@echo "... gemm_v1.s"
	@echo "... gemm_v1_alter.o"
	@echo "... gemm_v1_alter.i"
	@echo "... gemm_v1_alter.s"
	@echo "... gemm_v2.o"
	@echo "... gemm_v2.i"
	@echo "... gemm_v2.s"
	@echo "... gemm_v3.o"
	@echo "... gemm_v3.i"
	@echo "... gemm_v3.s"
	@echo "... gemm_v4.o"
	@echo "... gemm_v4.i"
	@echo "... gemm_v4.s"
	@echo "... gemm_v5.o"
	@echo "... gemm_v5.i"
	@echo "... gemm_v5.s"
	@echo "... gemm_v6.o"
	@echo "... gemm_v6.i"
	@echo "... gemm_v6.s"
	@echo "... gemm_v6_alter.o"
	@echo "... gemm_v6_alter.i"
	@echo "... gemm_v6_alter.s"
	@echo "... gemm_v7.o"
	@echo "... gemm_v7.i"
	@echo "... gemm_v7.s"
	@echo "... gemm_v7_alter.o"
	@echo "... gemm_v7_alter.i"
	@echo "... gemm_v7_alter.s"
	@echo "... gemm_v8.o"
	@echo "... gemm_v8.i"
	@echo "... gemm_v8.s"
	@echo "... gemm_v8_alter.o"
	@echo "... gemm_v8_alter.i"
	@echo "... gemm_v8_alter.s"
	@echo "... gemm_v9.o"
	@echo "... gemm_v9.i"
	@echo "... gemm_v9.s"
	@echo "... gemm_v9_alter.o"
	@echo "... gemm_v9_alter.i"
	@echo "... gemm_v9_alter.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

